name: citra-ci

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container: 
      image: citraemu/build-environments:linux-clang-format
      options: -u 1001
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Build
        env:
          COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
        run: ./.ci/linux-clang-format/docker.sh
  source:
    if: ${{ !github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Pack
        run: ./.ci/source/build.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: artifacts/
  ios:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: ["Release", "RelWithDebInfo"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: brew install glslang
      # Currently ccache is commented out since I don't know how to use it with Xcode + CMake
      # - name: Set up cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/Library/Caches/ccache
      #     key: ${{ runner.os }}-macos-${{ matrix.arch }}-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-macos-${{ matrix.arch }}-
      - name: Query tag name
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
      - name: Download MoltenVK
        run: |
          mkdir -p build/dependencies
          cd build/dependencies
          # https://github.com/KhronosGroup/MoltenVK/actions/runs/4496704187
          # TODO: we should not to depend nightly.link, use GH actions token instead
          # If this link was dead, i have a archive: https://web.archive.org/web/20230418172358/https://nightly.link/KhronosGroup/MoltenVK/suites/11749022866/artifacts/612167163
          # but most good choice is take from latest release's artifact https://github.com/KhronosGroup/MoltenVK/releases
          curl -Lo ios.zip https://nightly.link/KhronosGroup/MoltenVK/suites/11749022866/artifacts/612167163
          unzip ios.zip
          tar xf ios.tar
      - name: Build
        run: |
          ./build_ios.sh
          xcodebuild -configuration "${{ matrix.configuration }}" -scheme citra_ios -project build/ios/citra.xcodeproj CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          cd build/ios/bin/"${{ matrix.configuration }}"
          mkdir -p ipa/Payload
          cp -cr citra_ios.app ./ipa/Payload/citra_ios.app
          cd ipa
          codesign -f -s - ./Payload/citra_ios.app/Frameworks/*
          codesign -f -s - --entitlements ${{ github.workspace }}/src/citra_ios/resources/entitlements.plist ./Payload/citra_ios.app
          mkdir -p ${{ github.workspace }}/artifacts
          zip -r ${{ github.workspace }}/artifacts/citra_ios_ci_${{ github.run_id }}_${{ matrix.configuration }}_${{ github.sha }}.ipa .
        env:
          DEVELOPMENT_TEAM_ID: "-"
          BUNDLE_IDENTIFIER: net.rinsuki.slapps.citra.ci-artifact
          MOLTENVK_IOS_ARTIFACT: "${{ github.workspace }}/build/dependencies/Package/Release/MoltenVK"
          CITRA_IOS_NAME_SUFFIX: " (CI)"
          CITRA_IOS_SHORT_VERSION: ".gha.${{ github.run_id }}.${{ matrix.configuration }}.${{ github.sha }}"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ios-${{ matrix.configuration }}
          path: artifacts/
  release_alpha:
    runs-on: macos-latest
    if: ${{ github.ref == 'refs/heads/ios_frontend' && github.event_name == 'push' }}
    needs:
    - ios
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ios-Release
          path: artifacts
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ios/alpha/${{ github.run_id }}
          release_name: "iOS (Î±) CI.${{ github.run_id }}"
          body: |
            ## NOTE
            * This version requires A12 or later device (iPhone XS/XR or later)
              * this is coming from GPU requirements (we need layered rendering)
            * This version can install to iOS 14 or later device, but...
              * We only supports latest stable iOS.
              * in iOS 14.x or older, you can't use virtual controller (which means you need to use external controller, like DS4 or Xbox or MFi certificated controller)
            * This version doesn't supporting these features:
              * Audio Input (Mic)
              * Camera
              * Motion Sensor
              * Touch Screen
              * NFC
              * SELECT/HOME button for physical controller
              * Circle Pad (including Pro), ZL/ZR, SELECT/START/HOME button for virtual controller
          draft: true
          prerelease: true
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/citra_ios_ci_${{ github.run_id }}_Release_${{ github.sha }}.ipa
          asset_name: citra_ios_ci_${{ github.run_id }}_Release_${{ github.sha }}.ipa
          asset_content_type: application/octet-stream